### ISSUE TITLE
Create file with txt extension

### ISSUE THREAD

**Issue by ISCLuisRamirez** [luiskrieg/PII201-test#6]
create file with txt extension and my name:

LuisRamirez.txt

**Comment by jalubc** [comment]
@ISCLuisRamirez  Rejected >=)
File must be named: LuisRamirez.txt

**Comment by jalubc** [comment]
@ISCLuisRamirez  Approved

**Comment by erickavila15** [comment]
Approved

**Comment by erickavila15** [comment]
@ISCLuisRamirez Approved
